### ISSUE TITLE
Flutter 3

### ISSUE THREAD

**Issue by xerz-one** [frealgagu/archlinux.flutter#21]
Hey, you probably have already noticed, but I'll open up a ticket to formalize the issue a bit more: the latest version of Flutter as of writing is 3.0.1. The AUR package should be updated to reflect this.

More information: https://medium.com/flutter/whats-new-in-flutter-3-8c74a5bc32d0

Related PR: https://github.com/frealgagu/archlinux.flutter/pull/19

**Comment by cosmopool** [comment]
I just created a pull request with the update to the latest version.

**Comment by xerz-one** [comment]
Welp that's weird, the version has been bumped up by 36051f1 while ignoring existing PRs as well as this ticket. Oh well, closing!
