### ISSUE TITLE
slow maintanence -> maybe some more maintainers

### ISSUE THREAD

**Issue by TheOneWithTheBraid** [frealgagu/archlinux.flutter#26]
Dear @frealgagu

I really like the work you put in the package. I'd anyway like to ask whether you might be open to accepting some more maintainers for the AUR Flutter package as well as this repository, as more maintainers could easily hold on with the fast release cycle. E.g. Flutter 3.0.2 was entirely skipped and never published in the AUR before that Flutter 3.0.3 was released yesterday.

Would you be willing to add e.g. @TheOneWithTheBraid or other interested contributors as maintainers for both this repo and the AUR package?

Thanks a lot!

**Comment by frealgagu** [comment]
Sure, I'm glad to have contributors, sometimes I'm busy and it's difficult to keep attention to AUR.
