### ISSUE TITLE
AUR update

### ISSUE THREAD

**Issue by AdrienLemaire** [frealgagu/archlinux.flutter#33]
Hi there,
The AUR package is flagged out of date
```
aur/flutter 3.0.3-1 (+100 3.98) (Out-of-date: 2022-07-01)
```
But I see you tagged a new version on this github repo 2 weeks ago. Can you update AUR with it ?

Thanks for maintaining this project!

**Comment by TheOneWithTheBraid** [comment]
I agree. I'd moreover like to point out to @frealgagu to avoid this in future by simply setting up #30.

**Comment by TheOneWithTheBraid** [comment]
@frealgagu Can you *plase* either push the current master to AUR *or* give me write access to the AUR (my username in there: `WithTheBraid`)? It seems like at the moment, I am usually faster with updating the PKGBUILD...

**Comment by frealgagu** [comment]
Permissions were added. Thank you for helping me to maintain this package.
